name: Checkstyle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle
        id: checkstyle
        run: |
          mvn checkstyle:check || echo "Checkstyle warnings found, but not failing the pipeline."
        continue-on-error: false

      - name: Mark job as warning if Checkstyle fails
        if: steps.checkstyle.outcome == 'failure'
        run: |
          echo "::warning file=checkstyle::Checkstyle found issues, review logs."
          exit 0
